"""
kestrion deploy --target k8s

Generates a Kubernetes manifest for running a Kestrion agent as a
stateless pod. The agent's state lives entirely in the SQLite store
(or Postgres once that's built), not in the process — so the pod is
genuinely stateless. That's the whole point of the event-sourcing
design; this command is just the packaging of that claim into something
you can actually `kubectl apply`.

What this generates, and why each piece:
- Deployment (1 replica default): stateless because state is in the
  store. Multiple replicas would need a shared Postgres store, which
  isn't built yet — 1 replica is the honest default for SQLite.
- ConfigMap: agent configuration (model, store URL, system prompt)
  separated from the image, following the 12-factor pattern.
- Secret (stub): placeholder for API keys — this command generates the
  shape, never actually contains a real key value, since secrets should
  never go into generated manifests.

Does NOT do: kubectl apply, cluster authentication, image building,
pushing to a registry. Those are your CI/CD pipeline's job. This just
gives you the manifests.
"""

from __future__ import annotations

MANIFEST_TEMPLATE = """\
# Generated by kestrion deploy --target k8s
# Review before applying. See comments for what to fill in.
#
# Apply with:
#   kubectl apply -f {output_file}
#
# Prerequisites:
#   - A container image with your agent code (see Dockerfile below)
#   - The image pushed to a registry your cluster can pull from
#   - A Kubernetes namespace to deploy into

---
apiVersion: v1
kind: Namespace
metadata:
  name: {namespace}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {name}-config
  namespace: {namespace}
data:
  KESTRION_MODEL: "{model}"
  KESTRION_STORE_URL: "{store_url}"
  KESTRION_SYSTEM_PROMPT: "{system_prompt}"

---
# IMPORTANT: Replace placeholder values with real secrets.
# Never commit real API keys to version control.
# Use a secrets manager (Vault, AWS Secrets Manager, etc.) in production.
apiVersion: v1
kind: Secret
metadata:
  name: {name}-secrets
  namespace: {namespace}
type: Opaque
stringData:
  LLM_API_KEY: "REPLACE_WITH_REAL_KEY"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: {namespace}
  labels:
    app: {name}
    managed-by: kestrion
spec:
  # 1 replica because SQLite is single-writer. Switch to Postgres and
  # increase this once kestrion[postgres] is available.
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: agent
          # Replace with your actual image:tag
          image: {image}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {name}-config
            - secretRef:
                name: {name}-secrets
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          # Mount a volume for the SQLite store if not using Postgres.
          # Remove this block when switching to a network-accessible store.
          volumeMounts:
            - name: store-volume
              mountPath: /data
      volumes:
        - name: store-volume
          # PersistentVolumeClaim for durable SQLite storage.
          # Change to emptyDir for ephemeral (state lost on pod restart).
          persistentVolumeClaim:
            claimName: {name}-store-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {name}-store-pvc
  namespace: {namespace}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Expose the agent if you've built an HTTP interface on top of it.
# Remove this if the agent runs as a background job with no HTTP surface.
apiVersion: v1
kind: Service
metadata:
  name: {name}-svc
  namespace: {namespace}
spec:
  selector:
    app: {name}
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
"""

DOCKERFILE_TEMPLATE = """\
# Dockerfile for a Kestrion agent.
# Place this in your project root alongside your agent script.

FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY pyproject.toml ./
RUN pip install --no-cache-dir kestrion[{provider}]

# Copy agent code
COPY {script} ./

# Store lives at /data — mount a volume here in production.
ENV KESTRION_STORE_URL="sqlite:////data/agent.db"

CMD ["python3", "{script}"]
"""


def generate_k8s_manifest(
    name: str,
    image: str,
    namespace: str,
    model: str,
    store_url: str,
    system_prompt: str,
    output_file: str,
) -> str:
    return MANIFEST_TEMPLATE.format(
        name=name,
        image=image,
        namespace=namespace,
        model=model,
        store_url=store_url,
        system_prompt=system_prompt,
        output_file=output_file,
    )


def generate_dockerfile(script: str, provider: str = "anthropic") -> str:
    return DOCKERFILE_TEMPLATE.format(script=script, provider=provider)