"""
kestrion — command line interface.

Entry point registered in pyproject.toml as:
    [project.scripts]
    kestrion = "kestrion.cli.main:main"

Commands:
    kestrion init              scaffold a new agent project
    kestrion run <file>        run an agent script
    kestrion deploy --target   generate deployment manifests

Uses stdlib argparse only — no click/typer dependency, consistent with
the project's "optional extras for optional things" philosophy.
"""

from __future__ import annotations

import argparse
import asyncio
import importlib.util
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# kestrion init
# ---------------------------------------------------------------------------

AGENT_TEMPLATE = '''\
"""
A Kestrion agent — generated by `kestrion init`.
Edit this file, then run it with `kestrion run agent.py`.
"""

import asyncio
from kestrion.agent.agent import Agent
from kestrion.agent.decorators import tool
from kestrion.llm.anthropic_provider import AnthropicProvider  # or OpenAI, Ollama


@tool
def get_status() -> dict:
    """Check the current status of something."""
    return {"status": "ok"}


@tool(requires_approval=True)
def do_something(target: str) -> dict:
    """Perform an action. Requires approval before executing."""
    return {"done": True, "target": target}


async def main():
    agent = Agent(
        provider=AnthropicProvider(model="claude-sonnet-4-6"),
        tools=[get_status, do_something],
        store="sqlite:///agent_runs.db",
    )
    result = await agent.run("Check the status and do something if needed.")
    print("status:", result.status)
    print("output:", result.output)


if __name__ == "__main__":
    asyncio.run(main())
'''

GITIGNORE_TEMPLATE = """\
# Kestrion
*.db
*.db-shm
*.db-wal
agent_runs.db

# Python
__pycache__/
*.pyc
.venv/
dist/
build/
"""


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.directory) if args.directory else Path.cwd()
    target.mkdir(parents=True, exist_ok=True)

    agent_file = target / "agent.py"
    gitignore_file = target / ".gitignore"

    if agent_file.exists() and not args.force:
        print(f"error: {agent_file} already exists. Use --force to overwrite.", file=sys.stderr)
        return 1

    agent_file.write_text(AGENT_TEMPLATE)
    print(f"created {agent_file}")

    if not gitignore_file.exists():
        gitignore_file.write_text(GITIGNORE_TEMPLATE)
        print(f"created {gitignore_file}")

    print()
    print("Next steps:")
    print(f"  cd {target}")
    print("  pip install kestrion[anthropic]   # or [openai] or [ollama]")
    print("  kestrion run agent.py")
    return 0


# ---------------------------------------------------------------------------
# kestrion run
# ---------------------------------------------------------------------------

def cmd_run(args: argparse.Namespace) -> int:
    script = Path(args.file)
    if not script.exists():
        print(f"error: {script} not found", file=sys.stderr)
        return 1

    # Load the module from the file path
    spec = importlib.util.spec_from_file_location("__kestrion_agent__", script)
    if spec is None or spec.loader is None:
        print(f"error: could not load {script}", file=sys.stderr)
        return 1

    # Add the script's directory to sys.path so relative imports work
    sys.path.insert(0, str(script.parent.resolve()))

    module = importlib.util.module_from_spec(spec)

    try:
        spec.loader.exec_module(module)
    except SystemExit:
        return 0
    except Exception as exc:
        print(f"error running {script}: {exc}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1

    # If the module has a main() coroutine, run it; otherwise the
    # exec_module above already ran the module's top-level code.
    if hasattr(module, "main") and asyncio.iscoroutinefunction(module.main):
        try:
            asyncio.run(module.main())
        except KeyboardInterrupt:
            print("\ninterrupted")
    return 0


# ---------------------------------------------------------------------------
# kestrion deploy
# ---------------------------------------------------------------------------

def cmd_deploy(args: argparse.Namespace) -> int:
    from kestrion.cli.deploy import generate_dockerfile, generate_k8s_manifest

    if args.target != "k8s":
        print(f"error: unsupported target '{args.target}'. Only 'k8s' is supported today.", file=sys.stderr)
        return 1

    name = args.name or Path.cwd().name.lower().replace("_", "-").replace(" ", "-")
    output = args.output or f"{name}-k8s.yaml"
    dockerfile_out = Path("Dockerfile")

    manifest = generate_k8s_manifest(
        name=name,
        image=args.image or f"your-registry/{name}:latest",
        namespace=args.namespace or "default",
        model=args.model or "claude-sonnet-4-6",
        store_url=args.store or "sqlite:////data/agent.db",
        system_prompt=args.system_prompt or "",
        output_file=output,
    )

    Path(output).write_text(manifest)
    print(f"generated {output}")

    if not dockerfile_out.exists() or args.force:
        script = args.file or "agent.py"
        provider = args.provider or "anthropic"
        dockerfile_out.write_text(generate_dockerfile(script=script, provider=provider))
        print("generated Dockerfile")

    print()
    print("Next steps:")
    print(f"  1. Fill in the real image name in {output} (search REPLACE_WITH_REAL_KEY too)")
    print("  2. Build and push your image:")
    print(f"       docker build -t your-registry/{name}:latest .")
    print(f"       docker push your-registry/{name}:latest")
    print("  3. Apply the manifest:")
    print(f"       kubectl apply -f {output}")
    return 0


# ---------------------------------------------------------------------------
# Main / argument parsing
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="kestrion",
        description="Kestrion — durable AI agent framework",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            examples:
              kestrion init                     scaffold a new agent in the current directory
              kestrion init ./my-agent          scaffold in a subdirectory
              kestrion run agent.py             run an agent script
              kestrion deploy --target k8s      generate Kubernetes manifests
        """),
    )
    parser.add_argument("--version", action="version", version="%(prog)s 0.2.1")

    sub = parser.add_subparsers(dest="command", metavar="<command>")

    # init
    p_init = sub.add_parser("init", help="scaffold a new Kestrion agent project")
    p_init.add_argument("directory", nargs="?", help="directory to scaffold into (default: current)")
    p_init.add_argument("--force", action="store_true", help="overwrite existing files")

    # run
    p_run = sub.add_parser("run", help="run an agent script")
    p_run.add_argument("file", help="path to the agent Python file")
    p_run.add_argument("-v", "--verbose", action="store_true", help="show full tracebacks on error")

    # deploy
    p_deploy = sub.add_parser("deploy", help="generate deployment manifests")
    p_deploy.add_argument("--target", required=True, choices=["k8s"], help="deployment target (only k8s for now)")
    p_deploy.add_argument("--name", help="agent/deployment name (default: current directory name)")
    p_deploy.add_argument("--image", help="container image (default: your-registry/<name>:latest)")
    p_deploy.add_argument("--namespace", default="default", help="Kubernetes namespace (default: default)")
    p_deploy.add_argument("--model", default="claude-sonnet-4-6", help="LLM model name")
    p_deploy.add_argument("--store", help="store URL (default: sqlite:////data/agent.db)")
    p_deploy.add_argument("--system-prompt", dest="system_prompt", default="", help="agent system prompt")
    p_deploy.add_argument("--file", help="agent script filename (for Dockerfile, default: agent.py)")
    p_deploy.add_argument("--provider", default="anthropic", help="LLM provider extra (for Dockerfile)")
    p_deploy.add_argument("--output", help="output filename (default: <name>-k8s.yaml)")
    p_deploy.add_argument("--force", action="store_true", help="overwrite existing Dockerfile")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    handlers = {
        "init": cmd_init,
        "run": cmd_run,
        "deploy": cmd_deploy,
    }
    sys.exit(handlers[args.command](args))


if __name__ == "__main__":
    main()