"""
kestrion — command line interface.

Entry point registered in pyproject.toml as:
    [project.scripts]
    kestrion = "kestrion.cli.main:main"

Commands:
    kestrion init              scaffold a new agent project
    kestrion run <file>        run an agent script
    kestrion deploy --target   generate deployment manifests

Uses stdlib argparse only — no click/typer dependency, consistent with
the project's "optional extras for optional things" philosophy.
"""

from __future__ import annotations

import argparse
import asyncio
import importlib.util
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# kestrion init
# ---------------------------------------------------------------------------

AGENT_TEMPLATE = '''\
"""
A Kestrion agent — generated by `kestrion init`.
Edit this file, then run it with `kestrion run agent.py`.
"""

import asyncio
from kestrion.agent.agent import Agent
from kestrion.agent.decorators import tool
from kestrion.llm.anthropic_provider import AnthropicProvider  # or OpenAI, Ollama


@tool
def get_status() -> dict:
    """Check the current status of something."""
    return {"status": "ok"}


@tool(requires_approval=True)
def do_something(target: str) -> dict:
    """Perform an action. Requires approval before executing."""
    return {"done": True, "target": target}


async def main():
    agent = Agent(
        provider=AnthropicProvider(model="claude-sonnet-4-6"),
        tools=[get_status, do_something],
        store="sqlite:///agent_runs.db",
    )
    result = await agent.run("Check the status and do something if needed.")
    print("status:", result.status)
    print("output:", result.output)


if __name__ == "__main__":
    asyncio.run(main())
'''

GITIGNORE_TEMPLATE = """\
# Kestrion
*.db
*.db-shm
*.db-wal
agent_runs.db

# Python
__pycache__/
*.pyc
.venv/
dist/
build/
"""


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.directory) if args.directory else Path.cwd()
    target.mkdir(parents=True, exist_ok=True)

    agent_file = target / "agent.py"
    gitignore_file = target / ".gitignore"

    if agent_file.exists() and not args.force:
        print(f"error: {agent_file} already exists. Use --force to overwrite.", file=sys.stderr)
        return 1

    agent_file.write_text(AGENT_TEMPLATE)
    print(f"created {agent_file}")

    if not gitignore_file.exists():
        gitignore_file.write_text(GITIGNORE_TEMPLATE)
        print(f"created {gitignore_file}")

    print()
    print("Next steps:")
    print(f"  cd {target}")
    print("  pip install kestrion[anthropic]   # or [openai] or [ollama]")
    print("  kestrion run agent.py")
    return 0


# ---------------------------------------------------------------------------
# kestrion run
# ---------------------------------------------------------------------------

def cmd_run(args: argparse.Namespace) -> int:
    script = Path(args.file)
    if not script.exists():
        print(f"error: {script} not found", file=sys.stderr)
        return 1

    # Load the module from the file path
    spec = importlib.util.spec_from_file_location("__kestrion_agent__", script)
    if spec is None or spec.loader is None:
        print(f"error: could not load {script}", file=sys.stderr)
        return 1

    # Add the script's directory to sys.path so relative imports work
    sys.path.insert(0, str(script.parent.resolve()))

    module = importlib.util.module_from_spec(spec)

    try:
        spec.loader.exec_module(module)
    except SystemExit:
        return 0
    except Exception as exc:
        print(f"error running {script}: {exc}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1

    # If the module has a main() coroutine, run it; otherwise the
    # exec_module above already ran the module's top-level code.
    if hasattr(module, "main") and asyncio.iscoroutinefunction(module.main):
        try:
            asyncio.run(module.main())
        except KeyboardInterrupt:
            print("\ninterrupted")
    return 0


# ---------------------------------------------------------------------------
# kestrion deploy
# ---------------------------------------------------------------------------

def cmd_deploy(args: argparse.Namespace) -> int:
    from kestrion.cli.deploy import generate_dockerfile, generate_k8s_manifest

    if args.target != "k8s":
        print(f"error: unsupported target '{args.target}'. Only 'k8s' is supported today.", file=sys.stderr)
        return 1

    name = args.name or Path.cwd().name.lower().replace("_", "-").replace(" ", "-")
    output = args.output or f"{name}-k8s.yaml"
    dockerfile_out = Path("Dockerfile")

    manifest = generate_k8s_manifest(
        name=name,
        image=args.image or f"your-registry/{name}:latest",
        namespace=args.namespace or "default",
        model=args.model or "claude-sonnet-4-6",
        store_url=args.store or "sqlite:////data/agent.db",
        system_prompt=args.system_prompt or "",
        output_file=output,
    )

    Path(output).write_text(manifest)
    print(f"generated {output}")

    if not dockerfile_out.exists() or args.force:
        script = args.file or "agent.py"
        provider = args.provider or "anthropic"
        dockerfile_out.write_text(generate_dockerfile(script=script, provider=provider))
        print("generated Dockerfile")

    print()
    print("Next steps:")
    print(f"  1. Fill in the real image name in {output} (search REPLACE_WITH_REAL_KEY too)")
    print("  2. Build and push your image:")
    print(f"       docker build -t your-registry/{name}:latest .")
    print(f"       docker push your-registry/{name}:latest")
    print("  3. Apply the manifest:")
    print(f"       kubectl apply -f {output}")
    return 0


def cmd_trace(args: argparse.Namespace) -> int:
    db_path = args.store or "kestrion_runs.db"
    db_file = Path(db_path)
    if not db_file.exists():
        if not args.store and Path("agent_runs.db").exists():
            db_path = "agent_runs.db"
            db_file = Path(db_path)
        else:
            print(f"error: database file '{db_path}' not found", file=sys.stderr)
            return 1

    from kestrion.store.sqlite_store import SQLiteCheckpointStore
    store = SQLiteCheckpointStore(path=db_path)

    async def get_data():
        events = await store.events_since(args.run_id, 0)
        checkpoint = await store.latest(args.run_id)
        return events, checkpoint

    try:
        events, checkpoint = asyncio.run(get_data())
    except Exception as exc:
        print(f"error loading run: {exc}", file=sys.stderr)
        return 1

    if not events:
        print(f"No events found for run_id: {args.run_id}", file=sys.stderr)
        return 1

    # ANSI colors
    C_GREEN = "\033[92m"
    C_YELLOW = "\033[93m"
    C_RED = "\033[91m"
    C_CYAN = "\033[96m"
    C_MAGENTA = "\033[95m"
    C_RESET = "\033[0m"
    C_BOLD = "\033[1m"

    state = checkpoint.state if checkpoint else None
    status = state.status.value if state else "UNKNOWN"
    total_tokens = state.total_tokens if state else 0
    total_cost = state.total_cost_usd if state else 0.0

    color = C_RESET
    if status == "completed":
        color = C_GREEN
    elif status == "waiting_on_human":
        color = C_YELLOW
    elif status == "failed":
        color = C_RED
    elif status == "expired":
        color = C_MAGENTA

    print(f"{C_BOLD}Run ID: {args.run_id}{C_RESET} ({color}{C_BOLD}{status.upper()}{C_RESET})")
    print(f"Database: {db_path}")
    print(f"Total Tokens: {total_tokens} | Cost: ${total_cost:.5f}")
    print("-" * 80)

    for evt in events:
        ts = evt.timestamp.strftime("%Y-%m-%d %H:%M:%S")
        evt_type = evt.type.value.upper()
        
        if "FAILED" in evt_type or "EXPIRED" in evt_type:
            type_color = C_RED
        elif "STARTED" in evt_type:
            type_color = C_GREEN
        elif "COMPLETED" in evt_type:
            type_color = C_CYAN
        elif "HUMAN" in evt_type:
            type_color = C_YELLOW
        else:
            type_color = C_RESET

        node_str = f" [{evt.node}]" if evt.node else ""
        print(f"[{ts}] {type_color}{C_BOLD}{evt_type}{C_RESET}{node_str}")

        payload = evt.payload
        if evt.type.value == "message_received":
            print(f"  {C_YELLOW}User Prompt:{C_RESET} {payload.get('content')}")
        elif evt.type.value == "llm_call_completed":
            print(f"  {C_CYAN}LLM Response:{C_RESET} Stop Reason: {payload.get('stop_reason')} | Tokens: {evt.tokens_in} in / {evt.tokens_out} out | Cost: ${evt.cost_usd:.5f}")
        elif evt.type.value == "tool_call_started":
            print(f"  {C_CYAN}Tool Call:{C_RESET} {payload.get('tool')}({payload.get('args')})")
        elif evt.type.value == "tool_call_completed":
            out_str = str(payload.get("output"))
            if len(out_str) > 120:
                out_str = out_str[:120] + "..."
            print(f"  {C_GREEN}Tool Output:{C_RESET} {out_str}")
        elif evt.type.value == "tool_call_failed":
            print(f"  {C_RED}Tool Error:{C_RESET} {payload.get('error')}")
        elif evt.type.value == "state_transition":
            from_node = payload.get("from")
            to_node = payload.get("to")
            print(f"  {C_MAGENTA}Transition:{C_RESET} {from_node} -> {to_node}")
        elif evt.type.value == "human_intervention":
            reason = payload.get("reason")
            tool = payload.get("tool")
            roles = payload.get("missing_roles")
            expires = payload.get("expires_at")
            print(f"  {C_YELLOW}Approval Required:{C_RESET} Tool '{tool}' | Missing Roles: {roles} | Expires: {expires}")
        elif evt.type.value == "checkpoint_saved":
            pass
        elif payload:
            print(f"  Payload: {payload}")
    return 0


def cmd_dashboard(args: argparse.Namespace) -> int:
    db_path = args.store or "kestrion_runs.db"
    db_file = Path(db_path)
    if not db_file.exists():
        if not args.store and Path("agent_runs.db").exists():
            db_path = "agent_runs.db"
            db_file = Path(db_path)

    from kestrion.cli.dashboard import start_dashboard
    start_dashboard(db_path=db_path, host=args.host, port=args.port)
    return 0


# ---------------------------------------------------------------------------
# Main / argument parsing
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="kestrion",
        description="Kestrion — durable AI agent framework",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            examples:
              kestrion init                     scaffold a new agent in the current directory
              kestrion init ./my-agent          scaffold in a subdirectory
              kestrion run agent.py             run an agent script
              kestrion deploy --target k8s      generate Kubernetes manifests
              kestrion trace <run_id>           view a run's event timeline
              kestrion dashboard                start the web dashboard
        """),
    )
    parser.add_argument("--version", action="version", version="%(prog)s 0.2.1")

    sub = parser.add_subparsers(dest="command", metavar="<command>")

    # init
    p_init = sub.add_parser("init", help="scaffold a new Kestrion agent project")
    p_init.add_argument("directory", nargs="?", help="directory to scaffold into (default: current)")
    p_init.add_argument("--force", action="store_true", help="overwrite existing files")

    # run
    p_run = sub.add_parser("run", help="run an agent script")
    p_run.add_argument("file", help="path to the agent Python file")
    p_run.add_argument("-v", "--verbose", action="store_true", help="show full tracebacks on error")

    # deploy
    p_deploy = sub.add_parser("deploy", help="generate deployment manifests")
    p_deploy.add_argument("--target", required=True, choices=["k8s"], help="deployment target (only k8s for now)")
    p_deploy.add_argument("--name", help="agent/deployment name (default: current directory name)")
    p_deploy.add_argument("--image", help="container image (default: your-registry/<name>:latest)")
    p_deploy.add_argument("--namespace", default="default", help="Kubernetes namespace (default: default)")
    p_deploy.add_argument("--model", default="claude-sonnet-4-6", help="LLM model name")
    p_deploy.add_argument("--store", help="store URL (default: sqlite:////data/agent.db)")
    p_deploy.add_argument("--system-prompt", dest="system_prompt", default="", help="agent system prompt")
    p_deploy.add_argument("--file", help="agent script filename (for Dockerfile, default: agent.py)")
    p_deploy.add_argument("--provider", default="anthropic", help="LLM provider extra (for Dockerfile)")
    p_deploy.add_argument("--output", help="output filename (default: <name>-k8s.yaml)")
    p_deploy.add_argument("--force", action="store_true", help="overwrite existing Dockerfile")

    # trace
    p_trace = sub.add_parser("trace", help="inspect a run's event timeline")
    p_trace.add_argument("run_id", help="the run ID to trace")
    p_trace.add_argument("--store", help="path to the SQLite database file (default: kestrion_runs.db)")

    # dashboard
    p_dash = sub.add_parser("dashboard", help="start the web dashboard server")
    p_dash.add_argument("--host", default="127.0.0.1", help="host to bind the server to (default: 127.0.0.1)")
    p_dash.add_argument("--port", type=int, default=8000, help="port to bind the server to (default: 8000)")
    p_dash.add_argument("--store", help="path to the SQLite database file (default: kestrion_runs.db)")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    handlers = {
        "init": cmd_init,
        "run": cmd_run,
        "deploy": cmd_deploy,
        "trace": cmd_trace,
        "dashboard": cmd_dashboard,
    }
    sys.exit(handlers[args.command](args))


if __name__ == "__main__":
    main()