"""
kestrion — command line interface.

Entry point registered in pyproject.toml as:
    [project.scripts]
    kestrion = "kestrion.cli.main:main"

Commands:
    kestrion init              scaffold a new agent project
    kestrion run <file>        run an agent script
    kestrion deploy --target   generate deployment manifests

Uses stdlib argparse only — no click/typer dependency, consistent with
the project's "optional extras for optional things" philosophy.
"""

from __future__ import annotations

import argparse
import asyncio
import importlib.util
import sys
import textwrap
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# kestrion init
# ---------------------------------------------------------------------------

AGENT_TEMPLATE = '''\
"""
A Kestrion agent — generated by `kestrion init`.
Edit this file, then run it with `kestrion run agent.py`.
"""

import asyncio
from kestrion.agent.agent import Agent
from kestrion.agent.decorators import tool
from kestrion.llm.anthropic_provider import AnthropicProvider  # or OpenAI, Ollama


@tool
def get_status() -> dict:
    """Check the current status of something."""
    return {"status": "ok"}


@tool(requires_approval=True)
def do_something(target: str) -> dict:
    """Perform an action. Requires approval before executing."""
    return {"done": True, "target": target}


async def main():
    agent = Agent(
        provider=AnthropicProvider(model="claude-sonnet-4-6"),
        tools=[get_status, do_something],
        store="sqlite:///agent_runs.db",
    )
    result = await agent.run("Check the status and do something if needed.")
    print("status:", result.status)
    print("output:", result.output)


if __name__ == "__main__":
    asyncio.run(main())
'''

GITIGNORE_TEMPLATE = """\
# Kestrion
*.db
*.db-shm
*.db-wal
agent_runs.db

# Python
__pycache__/
*.pyc
.venv/
dist/
build/
"""


def cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.directory) if args.directory else Path.cwd()
    target.mkdir(parents=True, exist_ok=True)

    agent_file = target / "agent.py"
    gitignore_file = target / ".gitignore"

    if agent_file.exists() and not args.force:
        print(f"error: {agent_file} already exists. Use --force to overwrite.", file=sys.stderr)
        return 1

    agent_file.write_text(AGENT_TEMPLATE)
    print(f"created {agent_file}")

    if not gitignore_file.exists():
        gitignore_file.write_text(GITIGNORE_TEMPLATE)
        print(f"created {gitignore_file}")

    print()
    print("Next steps:")
    print(f"  cd {target}")
    print("  pip install kestrion[anthropic]   # or [openai] or [ollama]")
    print("  kestrion run agent.py")
    return 0


# ---------------------------------------------------------------------------
# kestrion list
# ---------------------------------------------------------------------------

def cmd_list(args: argparse.Namespace) -> int:
    import sqlite3
    import json
    
    db_path = args.store or "kestrion_runs.db"
    db_file = Path(db_path)
    if not db_file.exists():
        if not args.store and Path("agent_runs.db").exists():
            db_path = "agent_runs.db"
        else:
            print(f"error: database file '{db_path}' not found", file=sys.stderr)
            return 1

    try:
        conn = sqlite3.connect(db_path)
        query = """
            SELECT c.run_id, c.created_at, c.state_blob
            FROM checkpoints c
            INNER JOIN (
                SELECT run_id, MAX(event_seq) as max_seq
                FROM checkpoints
                GROUP BY run_id
            ) latest ON c.run_id = latest.run_id AND c.event_seq = latest.max_seq
            ORDER BY c.created_at DESC
        """
        rows = conn.execute(query).fetchall()
    except Exception as exc:
        print(f"error listing runs: {exc}", file=sys.stderr)
        return 1
    finally:
        if 'conn' in locals():
            conn.close()

    # ANSI colors
    C_GREEN = "\033[92m"
    C_YELLOW = "\033[93m"
    C_RED = "\033[91m"
    C_MAGENTA = "\033[95m"
    C_CYAN = "\033[96m"
    C_RESET = "\033[0m"
    C_BOLD = "\033[1m"
    
    print(f"{C_BOLD}{'RUN ID':<36} | {'STATUS':<16} | {'COST':<8} | {'TOKENS':<8} | {'TIMESTAMP'}{C_RESET}")
    print("-" * 100)
    
    for row in rows:
        run_id, created_at, state_blob = row
        try:
            state = json.loads(state_blob)
            status = state.get("status", "unknown")
            cost = state.get("total_cost_usd", 0.0)
            tokens = state.get("total_tokens", 0)
            
            color = C_RESET
            if status == "completed":
                color = C_GREEN
            elif status == "waiting_on_human":
                color = C_YELLOW
            elif status == "failed":
                color = C_RED
            elif status == "expired":
                color = C_MAGENTA
            elif status == "running":
                color = C_CYAN
            
            print(f"{run_id:<36} | {color}{status.upper():<16}{C_RESET} | ${cost:<7.5f} | {tokens:<8} | {created_at}")
        except (json.JSONDecodeError, TypeError):
            print(f"{run_id:<36} | {'UNKNOWN':<16} | ${0.0:<7.5f} | {0:<8} | {created_at}")
            
    return 0


# ---------------------------------------------------------------------------
# kestrion run
# ---------------------------------------------------------------------------

def cmd_run(args: argparse.Namespace) -> int:
    script = Path(args.file)
    if not script.exists():
        print(f"error: {script} not found", file=sys.stderr)
        return 1

    # Load the module from the file path
    spec = importlib.util.spec_from_file_location("__kestrion_agent__", script)
    if spec is None or spec.loader is None:
        print(f"error: could not load {script}", file=sys.stderr)
        return 1

    # Add the script's directory to sys.path so relative imports work
    sys.path.insert(0, str(script.parent.resolve()))

    module = importlib.util.module_from_spec(spec)

    try:
        spec.loader.exec_module(module)
    except SystemExit:
        return 0
    except Exception as exc:
        print(f"error running {script}: {exc}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1

    # If the module has a main() coroutine, run it; otherwise the
    # exec_module above already ran the module's top-level code.
    if hasattr(module, "main") and asyncio.iscoroutinefunction(module.main):
        try:
            asyncio.run(module.main())
        except KeyboardInterrupt:
            print("\ninterrupted")
    return 0


# ---------------------------------------------------------------------------
# kestrion resume
# ---------------------------------------------------------------------------

def cmd_resume(args: argparse.Namespace) -> int:
    script = Path(args.file)
    if not script.exists():
        print(f"error: {script} not found", file=sys.stderr)
        return 1

    # Load the module from the file path
    spec = importlib.util.spec_from_file_location("__kestrion_agent__", script)
    if spec is None or spec.loader is None:
        print(f"error: could not load {script}", file=sys.stderr)
        return 1

    # Add the script's directory to sys.path so relative imports work
    sys.path.insert(0, str(script.parent.resolve()))
    module = importlib.util.module_from_spec(spec)

    # Intercept Agent.run to transparently call Agent.resume instead
    from kestrion.agent.agent import Agent
    async def fake_run(self, *a, **kw):
        print(f"Resuming run {args.run_id}...")
        return await self.resume(args.run_id)
    
    Agent.run = fake_run  # type: ignore[method-assign]

    try:
        spec.loader.exec_module(module)
    except SystemExit:
        return 0
    except Exception as exc:
        print(f"error running {script}: {exc}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1

    if hasattr(module, "main") and asyncio.iscoroutinefunction(module.main):
        try:
            asyncio.run(module.main())
        except KeyboardInterrupt:
            print("\ninterrupted")
    return 0


# ---------------------------------------------------------------------------
# kestrion chat
# ---------------------------------------------------------------------------

def cmd_chat(args: argparse.Namespace) -> int:
    script = Path(args.file)
    if not script.exists():
        print(f"error: {script} not found", file=sys.stderr)
        return 1

    spec = importlib.util.spec_from_file_location("__kestrion_agent__", script)
    if spec is None or spec.loader is None:
        print(f"error: could not load {script}", file=sys.stderr)
        return 1

    sys.path.insert(0, str(script.parent.resolve()))
    module = importlib.util.module_from_spec(spec)

    try:
        spec.loader.exec_module(module)
    except SystemExit:
        pass
    except Exception as exc:
        print(f"error loading {script}: {exc}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1

    from kestrion.agent.agent import Agent
    agent = None
    
    if hasattr(module, "agent") and isinstance(getattr(module, "agent"), Agent):
        agent = getattr(module, "agent")
    else:
        for val in vars(module).values():
            if isinstance(val, Agent):
                agent = val
                break
                
    if not agent and hasattr(module, "main") and asyncio.iscoroutinefunction(module.main):
        # The agent might be initialized inside main(). We can intercept Agent.run to capture it.
        original_run = Agent.run
        async def fake_run(self, *a, **kw):
            nonlocal agent
            agent = self
            raise RuntimeError("__STOP_KESTRION_CHAT__")
            
        Agent.run = fake_run  # type: ignore[method-assign]
        try:
            asyncio.run(module.main())
        except RuntimeError as e:
            if str(e) != "__STOP_KESTRION_CHAT__":
                pass
        except Exception:
            pass
        finally:
            Agent.run = original_run  # type: ignore[method-assign]
            
    if not agent:
        print(f"error: could not find an Agent instance in {script}", file=sys.stderr)
        print("Please define a top-level 'agent = Agent(...)' variable in your script.", file=sys.stderr)
        return 1

    # ANSI colors
    C_GREEN = "\033[92m"
    C_YELLOW = "\033[93m"
    C_RED = "\033[91m"
    C_CYAN = "\033[96m"
    C_MAGENTA = "\033[95m"
    C_RESET = "\033[0m"
    C_BOLD = "\033[1m"

    async def chat_loop():
        run_id = None
        messages = []
        
        print(f"{C_BOLD}Kestrion Interactive Chat{C_RESET} (Type /quit to exit)")
        print("-" * 50)
        
        while True:
            try:
                user_input = input(f"{C_CYAN}You:{C_RESET} ")
                if not user_input.strip():
                    continue
                if user_input.strip().lower() in ("/quit", "/exit", "quit", "exit"):
                    break
                    
                messages.append({"role": "user", "content": user_input})
                print(f"{C_GREEN}Agent is thinking...{C_RESET}", end="\r")
                
                result = await agent.run_with_history(messages, run_id=run_id)
                run_id = result.run_id
                
                # Clear the thinking line
                print(" " * 50, end="\r")
                
                if result.status.value == "waiting_on_human":
                    print(f"{C_YELLOW}Agent is paused and waiting for human approval.{C_RESET}")
                    
                    checkpoint = await agent._store.latest(run_id)
                    scratch = checkpoint.state.scratch if checkpoint else {}
                    messages = scratch.get("_messages", messages)
                    
                    last_msg = messages[-1] if messages else {}
                    tc_name = "unknown"
                    if last_msg.get("role") == "assistant" and last_msg.get("tool_calls"):
                        for tc in last_msg["tool_calls"]:
                            print(f"Tool: {tc['name']}({tc['arguments']})")
                            tc_name = tc["name"]
                            
                    approve_input = input("Approve this action? [y/N]: ")
                    if approve_input.lower().startswith('y'):
                        await agent.approve(run_id, tc_name, True)
                        print(f"{C_GREEN}Approved! Resuming...{C_RESET}")
                        result = await agent.resume(run_id)
                    else:
                        await agent.approve(run_id, tc_name, False)
                        print(f"{C_RED}Denied. Resuming...{C_RESET}")
                        result = await agent.resume(run_id)
                        
                if result.state and "_messages" in result.state.scratch:
                    messages = result.state.scratch["_messages"]
                    
                if result.output:
                    print(f"{C_MAGENTA}Agent:{C_RESET} {result.output}")
                elif result.status.value == "completed":
                    print(f"{C_MAGENTA}Agent:{C_RESET} (Completed with no output)")
                    
            except KeyboardInterrupt:
                print("\nInterrupted.")
                break
            except Exception as e:
                print(f"\n{C_RED}Error: {e}{C_RESET}")
                if args.verbose:
                    import traceback
                    traceback.print_exc()
                break
                
    asyncio.run(chat_loop())
    return 0


# ---------------------------------------------------------------------------
# kestrion deploy
# ---------------------------------------------------------------------------

def cmd_deploy(args: argparse.Namespace) -> int:
    from kestrion.cli.deploy import generate_dockerfile, generate_k8s_manifest

    if args.target != "k8s":
        print(f"error: unsupported target '{args.target}'. Only 'k8s' is supported today.", file=sys.stderr)
        return 1

    name = args.name or Path.cwd().name.lower().replace("_", "-").replace(" ", "-")
    output = args.output or f"{name}-k8s.yaml"
    dockerfile_out = Path("Dockerfile")

    manifest = generate_k8s_manifest(
        name=name,
        image=args.image or f"your-registry/{name}:latest",
        namespace=args.namespace or "default",
        model=args.model or "claude-sonnet-4-6",
        store_url=args.store or "sqlite:////data/agent.db",
        system_prompt=args.system_prompt or "",
        output_file=output,
    )

    Path(output).write_text(manifest)
    print(f"generated {output}")

    if not dockerfile_out.exists() or args.force:
        script = args.file or "agent.py"
        provider = args.provider or "anthropic"
        dockerfile_out.write_text(generate_dockerfile(script=script, provider=provider))
        print("generated Dockerfile")

    print()
    print("Next steps:")
    print(f"  1. Fill in the real image name in {output} (search REPLACE_WITH_REAL_KEY too)")
    print("  2. Build and push your image:")
    print(f"       docker build -t your-registry/{name}:latest .")
    print(f"       docker push your-registry/{name}:latest")
    print("  3. Apply the manifest:")
    print(f"       kubectl apply -f {output}")
    return 0

def generate_mermaid_flowchart(events: list[Any], run_id: str) -> str:
    lines = ["flowchart TD", f"    %% Mermaid trace for run {run_id}"]
    nodes_seen = set()
    node_labels = {}
    transitions = []
    action_counter = 0

    nodes_seen.add("START")
    node_labels["START"] = "START"

    def clean_id(name: str | None) -> str:
        if not name:
            return "engine"
        return "".join(c if c.isalnum() or c == "_" else "_" for c in name)

    last_active_node = "START"

    for evt in events:
        raw_node = evt.node or "engine"
        node_id = clean_id(raw_node)
        if node_id not in nodes_seen:
            nodes_seen.add(node_id)
            node_labels[node_id] = f"Node: {raw_node}"
            
        if evt.node:
            last_active_node = node_id

        evt_type = evt.type.value
        payload = evt.payload or {}

        if evt_type == "run_started":
            entry = clean_id(payload.get("entry_node") or "engine")
            if entry not in nodes_seen:
                nodes_seen.add(entry)
                node_labels[entry] = f"Node: {payload.get('entry_node') or 'engine'}"
            transitions.append(f"    START --> {entry}")
            last_active_node = entry
        elif evt_type == "state_transition":
            from_node = clean_id(payload.get("from") or "START")
            to_node = clean_id(payload.get("to") or "END")
            if from_node not in nodes_seen:
                nodes_seen.add(from_node)
                node_labels[from_node] = f"Node: {payload.get('from') or 'START'}"
            if to_node not in nodes_seen:
                nodes_seen.add(to_node)
                node_labels[to_node] = f"Node: {payload.get('to') or 'END'}"
            transitions.append(f"    {from_node} --> {to_node}")
            last_active_node = to_node
        elif evt_type == "tool_call_started":
            action_counter += 1
            tool_name = payload.get("tool", "unknown")
            tool_id = f"tool_{action_counter}"
            lines.append(f'    {tool_id}(["Tool: {tool_name}"])')
            transitions.append(f"    {node_id} --> {tool_id}")
        elif evt_type == "llm_call_completed":
            action_counter += 1
            llm_id = f"llm_{action_counter}"
            prompt_toks = evt.tokens_in
            comp_toks = evt.tokens_out
            lines.append(f'    {llm_id}{{"LLM Call<br/>{prompt_toks} in / {comp_toks} out"}}')
            transitions.append(f"    {node_id} --> {llm_id}")
        elif evt_type == "human_intervention":
            action_counter += 1
            human_id = f"human_{action_counter}"
            tool = payload.get("tool", "")
            lines.append(f'    {human_id}[/"Human Gate: {tool}"/]')
            transitions.append(f"    {node_id} --> {human_id}")
        elif evt_type == "context_compacted":
            action_counter += 1
            comp_id = f"comp_{action_counter}"
            lines.append(f'    {comp_id}("Context Compacted")')
            transitions.append(f"    {node_id} --> {comp_id}")
        elif evt_type == "run_completed":
            transitions.append(f"    {last_active_node} --> END")
        elif evt_type == "run_failed":
            transitions.append(f"    {last_active_node} --> FAILED")

    for n_id, label in node_labels.items():
        if n_id == "START":
            lines.append("    START([START])")
        else:
            lines.append(f'    {n_id}["{label}"]')

    unique_transitions = list(dict.fromkeys(transitions))
    lines.extend(unique_transitions)

    # Conditionally declare and style terminal nodes if they are reached
    has_end = any("--> END" in t for t in unique_transitions)
    has_failed = any("--> FAILED" in t for t in unique_transitions)

    if has_end:
        lines.append("    END([END])")
        lines.append("    style END fill:#10b981,stroke:#047857,stroke-width:2px,color:#fff")
    if has_failed:
        lines.append("    FAILED([FAILED])")
        lines.append("    style FAILED fill:#ef4444,stroke:#b91c1c,stroke-width:2px,color:#fff")

    # Stylize START node
    lines.append("    style START fill:#10b981,stroke:#047857,stroke-width:2px,color:#fff")

    return "\n".join(lines)


def cmd_trace(args: argparse.Namespace) -> int:
    db_path = args.store or "kestrion_runs.db"
    db_file = Path(db_path)
    if not db_file.exists():
        if not args.store and Path("agent_runs.db").exists():
            db_path = "agent_runs.db"
            db_file = Path(db_path)
        else:
            print(f"error: database file '{db_path}' not found", file=sys.stderr)
            return 1

    from kestrion.store.sqlite_store import SQLiteCheckpointStore
    store = SQLiteCheckpointStore(path=db_path)

    async def get_data():
        events = await store.events_since(args.run_id, 0)
        checkpoint = await store.latest(args.run_id)
        return events, checkpoint

    try:
        events, checkpoint = asyncio.run(get_data())
    except Exception as exc:
        print(f"error loading run: {exc}", file=sys.stderr)
        return 1

    if not events:
        print(f"No events found for run_id: {args.run_id}", file=sys.stderr)
        return 1

    if getattr(args, "mermaid", False):
        print(generate_mermaid_flowchart(events, args.run_id))
        return 0

    # ANSI colors
    C_GREEN = "\033[92m"
    C_YELLOW = "\033[93m"
    C_RED = "\033[91m"
    C_CYAN = "\033[96m"
    C_MAGENTA = "\033[95m"
    C_RESET = "\033[0m"
    C_BOLD = "\033[1m"

    state = checkpoint.state if checkpoint else None
    status = state.status.value if state else "UNKNOWN"
    total_tokens = state.total_tokens if state else 0
    total_cost = state.total_cost_usd if state else 0.0

    color = C_RESET
    if status == "completed":
        color = C_GREEN
    elif status == "waiting_on_human":
        color = C_YELLOW
    elif status == "failed":
        color = C_RED
    elif status == "expired":
        color = C_MAGENTA

    print(f"{C_BOLD}Run ID: {args.run_id}{C_RESET} ({color}{C_BOLD}{status.upper()}{C_RESET})")
    print(f"Database: {db_path}")
    print(f"Total Tokens: {total_tokens} | Cost: ${total_cost:.5f}")
    print("-" * 80)

    for evt in events:
        if args.type and evt.type.value != args.type:
            continue
        if args.node and evt.node != args.node:
            continue

        ts = evt.timestamp.strftime("%Y-%m-%d %H:%M:%S")
        evt_type = evt.type.value.upper()
        
        if "FAILED" in evt_type or "EXPIRED" in evt_type:
            type_color = C_RED
        elif "STARTED" in evt_type:
            type_color = C_GREEN
        elif "COMPLETED" in evt_type:
            type_color = C_CYAN
        elif "HUMAN" in evt_type:
            type_color = C_YELLOW
        else:
            type_color = C_RESET

        node_str = f" [{evt.node}]" if evt.node else ""
        print(f"[{ts}] {type_color}{C_BOLD}{evt_type}{C_RESET}{node_str}")

        payload = evt.payload
        if evt.type.value == "message_received":
            print(f"  {C_YELLOW}User Prompt:{C_RESET} {payload.get('content')}")
        elif evt.type.value == "llm_call_completed":
            print(f"  {C_CYAN}LLM Response:{C_RESET} Stop Reason: {payload.get('stop_reason')} | Tokens: {evt.tokens_in} in / {evt.tokens_out} out | Cost: ${evt.cost_usd:.5f}")
        elif evt.type.value == "tool_call_started":
            print(f"  {C_CYAN}Tool Call:{C_RESET} {payload.get('tool')}({payload.get('args')})")
        elif evt.type.value == "tool_call_completed":
            out_str = str(payload.get("output"))
            if len(out_str) > 120:
                out_str = out_str[:120] + "..."
            print(f"  {C_GREEN}Tool Output:{C_RESET} {out_str}")
        elif evt.type.value == "tool_call_failed":
            print(f"  {C_RED}Tool Error:{C_RESET} {payload.get('error')}")
        elif evt.type.value == "state_transition":
            from_node = payload.get("from")
            to_node = payload.get("to")
            print(f"  {C_MAGENTA}Transition:{C_RESET} {from_node} -> {to_node}")
        elif evt.type.value == "human_intervention":
            tool = payload.get("tool")
            roles = payload.get("missing_roles")
            expires = payload.get("expires_at")
            print(f"  {C_YELLOW}Approval Required:{C_RESET} Tool '{tool}' | Missing Roles: {roles} | Expires: {expires}")
        elif evt.type.value == "checkpoint_saved":
            pass
        elif payload:
            print(f"  Payload: {payload}")
    return 0


def cmd_dashboard(args: argparse.Namespace) -> int:
    db_path = args.store or "kestrion_runs.db"
    db_file = Path(db_path)
    if not db_file.exists():
        if not args.store and Path("agent_runs.db").exists():
            db_path = "agent_runs.db"
            db_file = Path(db_path)

    from kestrion.cli.dashboard import start_dashboard
    start_dashboard(db_path=db_path, host=args.host, port=args.port, script=args.file)
    return 0


def cmd_fork(args: argparse.Namespace) -> int:
    db_path = args.store or "kestrion_runs.db"
    db_file = Path(db_path)
    if not db_file.exists():
        if not args.store and Path("agent_runs.db").exists():
            db_path = "agent_runs.db"
            db_file = Path(db_path)
        else:
            print(f"error: database file '{db_path}' not found", file=sys.stderr)
            return 1

    from kestrion.store.sqlite_store import SQLiteCheckpointStore
    from kestrion.core.engine import Engine
    
    store = SQLiteCheckpointStore(path=db_path)
    # A dummy engine is sufficient since fork relies purely on the event log and store
    engine = Engine(nodes={}, tools={}, store=store, entry_node="dummy")
    
    try:
        new_run_id = asyncio.run(engine.fork(args.run_id, args.at_seq))
        print(f"Successfully forked run '{args.run_id}' up to sequence {args.at_seq}.")
        print(f"New Run ID: {new_run_id}")
        print(f"You can trace it using: kestrion trace {new_run_id}")
    except Exception as exc:
        print(f"error forking run: {exc}", file=sys.stderr)
        return 1
        
    return 0


# ---------------------------------------------------------------------------
# Main / argument parsing
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="kestrion",
        description="Kestrion — durable AI agent framework",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            examples:
              kestrion init                     scaffold a new agent in the current directory
              kestrion init ./my-agent          scaffold in a subdirectory
              kestrion run agent.py             run an agent script
              kestrion deploy --target k8s      generate Kubernetes manifests
              kestrion trace <run_id>           view a run's event timeline
              kestrion dashboard                start the web dashboard
        """),
    )
    try:
        import importlib.metadata
        version = importlib.metadata.version("kestrion")
    except Exception:
        version = "0.6.0"
    parser.add_argument("--version", action="version", version=f"%(prog)s {version}")

    sub = parser.add_subparsers(dest="command", metavar="<command>")

    # init
    p_init = sub.add_parser("init", help="scaffold a new Kestrion agent project")
    p_init.add_argument("directory", nargs="?", help="directory to scaffold into (default: current)")
    p_init.add_argument("--force", action="store_true", help="overwrite existing files")

    # run
    p_run = sub.add_parser("run", help="run an agent script")
    p_run.add_argument("file", help="path to the agent Python file")
    p_run.add_argument("-v", "--verbose", action="store_true", help="show full tracebacks on error")

    # deploy
    p_deploy = sub.add_parser("deploy", help="generate deployment manifests")
    p_deploy.add_argument("--target", required=True, choices=["k8s"], help="deployment target (only k8s for now)")
    p_deploy.add_argument("--name", help="agent/deployment name (default: current directory name)")
    p_deploy.add_argument("--image", help="container image (default: your-registry/<name>:latest)")
    p_deploy.add_argument("--namespace", default="default", help="Kubernetes namespace (default: default)")
    p_deploy.add_argument("--model", default="claude-sonnet-4-6", help="LLM model name")
    p_deploy.add_argument("--store", help="store URL (default: sqlite:////data/agent.db)")
    p_deploy.add_argument("--system-prompt", dest="system_prompt", default="", help="agent system prompt")
    p_deploy.add_argument("--file", help="agent script filename (for Dockerfile, default: agent.py)")
    p_deploy.add_argument("--provider", default="anthropic", help="LLM provider extra (for Dockerfile)")
    p_deploy.add_argument("--output", help="output filename (default: <name>-k8s.yaml)")
    p_deploy.add_argument("--force", action="store_true", help="overwrite existing Dockerfile")

    # trace
    p_trace = sub.add_parser("trace", help="inspect a run's event timeline")
    p_trace.add_argument("run_id", help="the run ID to trace")
    p_trace.add_argument("--store", help="path to the SQLite database file (default: kestrion_runs.db)")
    p_trace.add_argument("--type", help="filter events by type (e.g. tool_call_started)")
    p_trace.add_argument("--node", help="filter events by node (e.g. agent_loop)")
    p_trace.add_argument("--mermaid", action="store_true", help="output trace as a Mermaid flowchart diagram")

    # list
    p_list = sub.add_parser("list", help="list all runs in the database")
    p_list.add_argument("--store", help="path to the SQLite database file (default: kestrion_runs.db)")

    # resume
    p_resume = sub.add_parser("resume", help="resume a paused or crashed run")
    p_resume.add_argument("run_id", help="the run ID to resume")
    p_resume.add_argument("file", help="path to the agent Python file")
    p_resume.add_argument("-v", "--verbose", action="store_true", help="show full tracebacks on error")

    # chat
    p_chat = sub.add_parser("chat", help="interactively chat with an agent")
    p_chat.add_argument("file", help="path to the agent Python file")
    p_chat.add_argument("-v", "--verbose", action="store_true", help="show full tracebacks on error")

    # dashboard
    p_dash = sub.add_parser("dashboard", help="start the web dashboard server")
    p_dash.add_argument("file", nargs="?", help="optional path to the agent Python file for interactive chat")
    p_dash.add_argument("--host", default="127.0.0.1", help="host to bind the server to (default: 127.0.0.1)")
    p_dash.add_argument("--port", type=int, default=8000, help="port to bind the server to (default: 8000)")
    p_dash.add_argument("--store", help="path to the SQLite database file (default: kestrion_runs.db)")

    # fork
    p_fork = sub.add_parser("fork", help="time-travel by branching off a past run")
    p_fork.add_argument("run_id", help="the run ID to fork")
    p_fork.add_argument("--at-seq", type=int, required=True, help="the event sequence count to fork at")
    p_fork.add_argument("--store", help="path to the SQLite database file (default: kestrion_runs.db)")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    handlers = {
        "init": cmd_init,
        "run": cmd_run,
        "deploy": cmd_deploy,
        "trace": cmd_trace,
        "dashboard": cmd_dashboard,
        "fork": cmd_fork,
        "list": cmd_list,
        "resume": cmd_resume,
        "chat": cmd_chat,
    }
    sys.exit(handlers[args.command](args))


if __name__ == "__main__":
    main()