"""
A Kestrion agent — generated by `kestrion init`.
Edit this file, then run it with `kestrion run agent.py`.
"""

import asyncio
from kestrion.agent.agent import Agent
from kestrion.agent.decorators import tool
from kestrion.llm.anthropic_provider import AnthropicProvider  # or OpenAI, Ollama


@tool
def get_status() -> dict:
    """Check the current status of something."""
    return {"status": "ok"}


@tool(requires_approval=True)
def do_something(target: str) -> dict:
    """Perform an action. Requires approval before executing."""
    return {"done": True, "target": target}


async def main():
    agent = Agent(
        provider=AnthropicProvider(model="claude-sonnet-4-6"),
        tools=[get_status, do_something],
        store="sqlite:///agent_runs.db",
    )
    result = await agent.run("Check the status and do something if needed.")
    print("status:", result.status)
    print("output:", result.output)


if __name__ == "__main__":
    asyncio.run(main())
